// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqxpvwakdcuzmeerfyhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xeHB2d2FrZGN1em1lZXJmeWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODQ5MjAsImV4cCI6MjA2MDg2MDkyMH0.FxR-X4bXhvZsVAw9957ivKS3vuhupuqiApW_wb9nY5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);